PAP_1.1/PAP.Web/DevCommunity2.Web/Controllers/FeedController.cs
using System;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PAP.Business.Managers;
using PAP.Business.Persistence.Repositories;
using PAP.Business.Repositories;
using PAP.Business.ViewModels;

namespace DevCommunity2.Web.Controllers
{
    [Authorize]
    public class FeedController : Controller
    {
        private readonly PublishAccountRepository _PublishAccountRepo;
        private readonly BaseManager _BaseManager;
        private readonly HostingEnvironment _hostingEnvironment;
    

        public FeedController(IPublishAccountRepository PublishAccountRepo, BaseManager baseManager, IHostingEnvironment hostingEnvironment)
        {
            _PublishAccountRepo = (PublishAccountRepository)PublishAccountRepo;
            _BaseManager = baseManager;
            _hostingEnvironment = (HostingEnvironment)hostingEnvironment;
        }     
        // GET: Feed
        public ActionResult Index()
        {
           
            var result = _PublishAccountRepo.GetAccountPublishes().ToList();
            return View(result);
        }

        // GET: Feed/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Feed/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(FeedPostViewModel FeedPost, IFormFile File)
        {
            try
            {
                Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out Guid userId);
                if (File != null)
                {
                    var uploadFolder = Path.Combine(
                        _hostingEnvironment.WebRootPath, "Images", "AccountPublish");
                    var uniqueFileName = Guid.NewGuid() + File.FileName;

                    var path = Path.Combine(uploadFolder, uniqueFileName);


                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await File.CopyToAsync(stream);
                    }
               
                    string pic = System.IO.Path.GetFileName(File.FileName);

                    FeedPost.Path = uniqueFileName;
                }
                _PublishAccountRepo.AddAccountPublish(FeedPost, userId);
                _BaseManager.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return Json(new { success = false, message = "erro" });
                throw;
            }

        }
   
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateFeedBack(FeedIndexViewModel feedIndexViewModel)
        {
            Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out Guid userId);

            if (userId == null)
            {
                return Json(new { success = false, message = "erro" });
            }

            var fifvm = new FeedIndexFeedBackViewModel()
            {
                AccountPublishId = feedIndexViewModel.AccountPublishId,
                FeedBackText = feedIndexViewModel.FeedBackText
            };

            try
            {
                
                _PublishAccountRepo.AddFeedBack(fifvm, userId);
                _BaseManager.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return BadRequest();
                throw;
            }
        }           
    }
}

PAP_1.1/PAP.Web/DevCommunity2.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PAP.Business.Persistence.Repositories;
using PAP.Business.Repositories;

namespace DevCommunity2.Web.Controllers
{

    [Authorize]
    public class UserController : Controller
    {

        private readonly AccountRepository _accountRepository;

        public UserController(IAccountRepository accountRepo)
        {
            _accountRepository = (AccountRepository)accountRepo;
        }

        [HttpPost]
        public JsonResult GetUserPhoto()
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value;
            if (string.IsNullOrEmpty(userId))
            {
                return Json("ERRO");
            }

            var user = _accountRepository.GetUserInfo(new Guid(userId));

            if (user == null)
            {
                return Json("ERRO");
            }
            string userPhoto = "/Images/UserPhotos/" + user.PhotoUrl;
            return Json(userPhoto);
        }

        [HttpPost]
        public JsonResult GetNickName()
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value;
            if (string.IsNullOrEmpty(userId))
            {
                return Json("Bad Request");
            }

            var user = _accountRepository.GetUserInfo(new Guid(userId));

            if (user == null)
            {
                return Json("Bad Request");
            }
            return Json(user.Nickname);
        }
    }
}

PAP_1.1/PAP.Web/DevCommunity2.Web/Views/Shared/LayoutAuth.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <environment include="Development">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <script src="~/bundles/jquery"></script>
        <script src="~/bundles/jqueryval"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
        <!-- Material Design Bootstrap -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.2/css/mdb.min.css" rel="stylesheet">
        <!-- JQuery -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <!-- Bootstrap tooltips -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <!-- MDB core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.2/js/mdb.min.js"></script>

        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

        <link rel="stylesheet" href="~/css/LayoutAuth.css" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark  bg-primary border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-controller="Feed" asp-action="Index">DevCommunity</a>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>
    <script>

        $(function () {
            $.ajax({
                type: "POST",
                url: "@Url.Action("GetUserPhoto", "User")",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    if (response != null) {
                        $(".user-photo").attr("src", response);
                    }
                    else {
                          $(".user-photo").attr("src","~/Images/UserPhotos/DefaultUserPhoto.png" );
                    }
                }
            })
        })

            $(function () {
            $.ajax({
                type: "POST",
                url: "@Url.Action("GetNickName", "User")",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    if (response != null) {
                        $(".nick-name").text(response);
                    }
                    else {
                        $(".nick-name").text("User Name");
                    }
                }
            })
        })
    </script>
    @RenderSection("ScriptsAuth", required: false)

</body>
</html>

PAP_1.1/PAP.Web/DevCommunity2.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DevCommunity</title>

    <environment include="Development">
        <script src="https://apis.google.com/js/platform.js" async defer></script>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
        <!-- Material Design Bootstrap -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.2/css/mdb.min.css" rel="stylesheet">
        <!-- JQuery -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <!-- Bootstrap tooltips -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <!-- MDB core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.2/js/mdb.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/TweenMax.min.js"></script>
        
        <link rel="stylesheet" href="~/css/LayoutAuth.css" />
    
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark  bg-primary border-bottom box-shadow mb-3">
            <div class="container">
             <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DevCommunity</a>               
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
 
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>