PAP_1.1/PAP.Web/DevCommunity2.Web/Controllers/EventController.cs
using System;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PAP.Business.Managers;
using PAP.Business.Persistence.Repositories;
using PAP.Business.Repositories;
using PAP.Business.ViewModels;

namespace DevCommunity2.Web.Controllers
{
    [Authorize]
    public class EventController : Controller
    {

        private readonly EventRepository _eventRepo;
        private readonly BaseManager _BaseManager;

        public EventController(IEventRepository eventRepo, BaseManager baseManager)
        {
            _eventRepo = (EventRepository)eventRepo;
            _BaseManager = baseManager;
        }


        
        [HttpPost]
        public ActionResult JoinOnEvent(int eventId)
        {
            Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out Guid userId);

            if (userId == null)
            {
                return Json(new { sucess = false });
            }

            _eventRepo.JoinOnEvent(eventId, userId);
            _BaseManager.SaveChanges();

             return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        public ActionResult UnJoinOnEvent(int eventId)
        {
            Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out Guid userId);

            if (userId == null)
            {
                return Json(new { sucess = false });
            }

            _eventRepo.UnJoinEvent(eventId, userId);
            _BaseManager.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // GET: Event
        public ActionResult Index()
        {
            Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out Guid userId);
            if (userId != null )
            {
                return View(_eventRepo.GetAll(userId));
            }
            return View();
        }    

        // GET: Event/Create
        
        public ActionResult Create()
        {
            return View();
        }
      
        // POST: Event/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EventViewModel @event)
        {
           
                //  string userid = User.
                //Guid.TryParse(userid, out Guid usertst);
                // TODO: Add insert logic here     
                Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out Guid userId);
                _eventRepo.Add(@event, userId);
                _BaseManager.SaveChanges();
                return RedirectToAction(nameof(Index));
            
           
        }

        // GET: Event/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {

                return View();
            }
            catch (Exception)
            {
                return View();
                throw;
            }
        }

        // POST: Event/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EventViewModel @event, int id)
        {
            // TODO: Add update logic here
            try
            {
                @event.EventId = id;
                _eventRepo.EditEvent(@event);
                _BaseManager.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return View();
                throw;
            }
        }

        // GET: Event/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Event/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(EventViewModel @event)
        {
            try
            {
                // TODO: Add delete logic here
                //_eventRepo.Remove(@event);
                //_eventRepo.Complete();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PAP_1.1/PAP.Web/DevCommunity2.Web/Controllers/EventFeedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PAP.Business.Managers;
using PAP.Business.Persistence.Repositories;
using PAP.Business.Repositories;
using PAP.Business.ViewModels;
using PAP.Business.ViewModels.Event;

namespace DevCommunity2.Web.Controllers
{
    public class EventFeedController : Controller
    {
        private readonly PublishEventRepository _publishEventRepository;
        private readonly BaseManager _BaseManager;
        private readonly HostingEnvironment _hostingEnvironment;
       


        public EventFeedController(IPublishEventRepository publishEventRepository, BaseManager baseManager, IHostingEnvironment hostingEnvironment)
        {
            _publishEventRepository = (PublishEventRepository)publishEventRepository;
            _BaseManager = baseManager;
            _hostingEnvironment = (HostingEnvironment)hostingEnvironment;
        }

        public ActionResult Index(int EventId)
        {

            if (EventId == 0)
            {
                EventId = (int)TempData["EventId"]; 
            }
            if (EventId != 0)
             {
                var result = _publishEventRepository.GetEventPublishes(EventId).ToList();
                TempData["EventId"] = EventId;
               
                return View(result);
            }
            return BadRequest();
        }

        // GET: Feed/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Feed/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(EventPostViewModel FeedPost, IFormFile File)
        {
            try
            {
                Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out Guid userId);

                if (File != null)
                {

                    var uploadFolder = Path.Combine(
                        _hostingEnvironment.WebRootPath, "Images", "PublishEvent");
                    var uniqueFileName = Guid.NewGuid() + File.FileName;

                    var path = Path.Combine(uploadFolder, uniqueFileName);


                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await File.CopyToAsync(stream);
                    }
                    string pic = System.IO.Path.GetFileName(File.FileName);

                    FeedPost.Path = uniqueFileName;
                }
                FeedPost.EventId = int.Parse(TempData["EventId"].ToString());

                TempData.Keep("EventId");
                _publishEventRepository.AddEventPublish(FeedPost, userId, FeedPost.EventId);
                _BaseManager.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return Json(new { success = false, message = "erro" });
                throw;
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateFeedBack(EventFeedIndexViewModel feedIndexViewModel)
        {
            Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out Guid userId);

            if (userId == null)
            {
                return Json(new { success = false, message = "erro" });
            }

            var fifvm = new EventFeedIndexFeedBackViewModel()
            {
                EventPublishId = feedIndexViewModel.AccountPublishId,
                EventFeedBackText = feedIndexViewModel.FeedBackText
            };

            try
            {

                _publishEventRepository.AddFeedBack(fifvm, userId);
                _BaseManager.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return BadRequest();
                throw;
            }
        }
    }
}

PAP_1.1/PAP.Web/DevCommunity2.Web/Views/Event/Create.cshtml
@model PAP.Business.ViewModels.EventViewModel

@{
    Layout = "~/Views/Shared/LayoutAuth.cshtml";
}

<body>  
        <br />
        <div class="card">
            <h5 class="card-header info-color white-text text-center py-4">
                <strong>New Event</strong>
            </h5>

            <!--Card content-->
            <div class="card-body px-lg-5 pt-0">

                <!-- Form -->
                <form asp-controller="Event" asp-action="Create" class="text-center" style="color: #757575;">

                    @Html.AntiForgeryToken()

                    <!-- Name -->
                    <div class="md-form mt-3">                      
                        <input asp-for="EventName" type="text" id="materialContactFormName" placeholder="Name" class="form-control">
                    </div>


                    <!--Description-->
                    <div class="md-form">
                        <textarea id="materialContactFormMessage" asp-for="Description" class="form-control md-textarea" rows="3"></textarea>
                        <label for="materialContactFormMessage">Description</label>
                    </div>

                    <!-- EventDate -->
                    <div class="md-form">
                        <input type="date" asp-for="EventDate" id="materialContactFormEmail" placeholder="Date" class="form-control">
                    </div>


                    <div class="md-form">
                        <input type="text" asp-for="Location" id="materialContactFormEmail" placeholder="Location" class="form-control">
                    </div>

                    <!-- Send button -->
                    <button class="btn btn-outline-info btn-rounded btn-block z-depth-0 my-4 waves-effect" type="submit">Create</button>

                </form>
                <!-- Form -->

            </div>

        </div>     
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>

PAP_1.1/PAP.Web/DevCommunity2.Web/Views/Event/Edit.cshtml
@model PAP.Business.ViewModels.EventViewModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/LayoutAuth.cshtml";
}

@using (Html.BeginForm())
{
    <div class="card">
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.EventId)
        <!-- Name -->
        <div class="md-form mt-3">
            <input asp-for="EventName" type="text" id="materialContactFormName" placeholder="Name" class="form-control">
            @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
        </div>


        <!--Description-->
        <div class="md-form">
            <textarea id="materialContactFormMessage" asp-for="Description" class="form-control md-textarea" rows="3"></textarea>
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            <label for="materialContactFormMessage">Description</label>
        </div>

        <!-- EventDate -->
        <div class="md-form">
            <input type="date" asp-for="EventDate" id="materialContactFormEmail" placeholder="Date" class="form-control">
            @Html.ValidationMessageFor(model => model.EventDate, "", new { @class = "text-danger" })

        </div>


        <div class="md-form">
            <input type="text" asp-for="Location" id="materialContactFormEmail" placeholder="Location" class="form-control">
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-outline-info btn-rounded btn-block z-depth-0 my-4 waves-effect" type="submit">Edit</button>
            </div>
        </div>
    </div>
}

PAP_1.1/PAP.Web/DevCommunity2.Web/Views/Event/Index.cshtml
@model IEnumerable<PAP.Business.ViewModels.EventViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/LayoutAuth.cshtml";
}

<br />
<form>
    <button asp-action="Create" asp-controller="Event" class="btn btn-primary"> Create new </button>
</form>

@foreach (var item in Model)
{
    <br />
    <div class="card">
        <div class="card text-center">
            <div class="card-header">
                <p class="card-title">
                    @Html.ActionLink(@item.EventName, "Index", "EventFeed", new { EventId = item.EventId })                 
                </p>
            </div>
            <div class="card-body">
                <p class="card-text">@item.Description</p>
                <p class="card-text">@item.Location</p>
                @if (item.IsUserCreated)
                {
                    @Html.ActionLink("Edit", "Edit", new { @class = "btn btn-primary", id = item.EventId })
                }

            </div>
            <div class="card-footer text-muted">
                <span style="color:red">Event Date : @item.EventDate.ToShortDateString()</span>
            </div>
        </div>
    </div>

}